# sarasas=[1,5,"petras",8,15]
# print(sarasas)
# sarasas.append("Ariogala")
# print(sarasas)
# sarasas[2]="Merkys"
# print(sarasas)
# sarasas.pop(3)
# print(sarasas)
# sarasas.remove("Ariogala")
# print(sarasas)
# sarasas.clear()
# print(sarasas)
# sarasas.extend("15 morku")
# print(sarasas)
# sarasas.pop(6)
# print(sarasas)
# sarasas.pop(7)
# print(sarasas)
# sarasas.pop(7)
# sarasas.pop(8)
# print(sarasas)
# sarasas.pop(6)
# sarasas.pop(7)
# print(sarasas)
# sarasas.clear()
sarasas=[1, 5, 'Merkys', 8, 15, 'Ariogala']
# sarasas.insert(2,"vytis")
print(sarasas)
sarasas.insert(2, "vytis")
print(sarasas)
